# Generated by Django 6.0.5 on 2026-06-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_serviceprovider_is_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='services_offered',
            field=models.TextField(blank=True, default=''),
        ),
    ]
