# Generated by Django 6.0.5 on 2026-05-07 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAssistant',
            fields=[
                ('ai_id', models.AutoField(primary_key=True, serialize=False)),
                ('ai_name', models.CharField(max_length=100)),
                ('purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('activation_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_assistant',
            },
        ),
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('ai_conversation_id', models.AutoField(primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_analysis', models.JSONField(blank=True, null=True)),
                ('ai', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ai_assistant.aiassistant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_conversation',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('ai_message_id', models.AutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('user', 'User'), ('ai', 'AI')], max_length=10)),
                ('input_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('voice', 'Voice')], default='text', max_length=10)),
                ('content', models.TextField(blank=True)),
                ('media_url', models.URLField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_assistant.aiconversation')),
            ],
            options={
                'db_table': 'ai_message',
                'ordering': ['sent_at'],
            },
        ),
    ]
