# Generated by Django 6.0.5 on 2026-05-07 12:45

import apps.services.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('service_request_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='requests/%Y/%m/', validators=[apps.services.models._validate_file_size])),
                ('voice_note', models.FileField(blank=True, null=True, upload_to='voices/%Y/%m/', validators=[apps.services.models._validate_file_size])),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('current_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to='accounts.serviceprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'service_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=150)),
                ('service_description', models.TextField(blank=True, null=True)),
                ('service_date', models.DateField()),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='accounts.serviceprovider')),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='services.servicerequest')),
            ],
            options={
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestStatusTracking',
            fields=[
                ('tracking_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('status_date', models.DateTimeField(auto_now_add=True)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='services.servicerequest')),
            ],
            options={
                'db_table': 'service_request_status_tracking',
                'ordering': ['-status_date'],
            },
        ),
        migrations.CreateModel(
            name='SavedProvider',
            fields=[
                ('saved_id', models.AutoField(primary_key=True, serialize=False)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='accounts.serviceprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_providers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_provider',
                'ordering': ['-saved_at'],
                'unique_together': {('user', 'service_provider')},
            },
        ),
    ]
