# Generated by Django 6.0.5 on 2026-05-07 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('ai_assistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProviderSchedule',
            fields=[
                ('service_provider_schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('working_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('ai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_schedules', to='ai_assistant.aiassistant')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='accounts.serviceprovider')),
            ],
            options={
                'db_table': 'service_provider_schedule',
                'ordering': ['working_date', 'start_time'],
            },
        ),
    ]
