# Generated by Django 6.0.5 on 2026-06-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='service_category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
