# Generated by Django 6.0.5 on 2026-06-07 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_conversation_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_request_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
